enum TipoVehiculo {
    AUTOMOVIL, BICICLETA, MOTOCICLETA
}

enum Estado {
    DESOCUPADO, OCUPADO, POR_OCUPAR, POR_DESOCUPAR, RESERVADO
}

enum MetodoPago {
    EFECTIVO, TRANSFERENCIA, TARJETA
}
